# This file was generated by the {rix} R package v0.16.0 on 2025-11-02
# with following call:
# >rix(date = "2025-10-27",
#  > r_pkgs = c("quarto",
#  > "MASS"),
#  > system_pkgs = "quarto",
#  > tex_pkgs = c("scheme-medium",
#  > "fontawesome5",
#  > "orcidlink",
#  > "pdfcol",
#  > "tcolorbox",
#  > "tikzfill",
#  > "fancyhdr",
#  > "titling",
#  > "csquotes",
#  > "makecell",
#  > "threeparttable",
#  > "threeparttablex",
#  > "pdflscape",
#  > "fontspec",
#  > "collection-fontsextra"),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE,
#  > shell_hook = "",
#  > r_ver = "4.5.1")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-10-27.tar.gz") {};
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      collection-fontsextra
      csquotes
      fancyhdr
      fontawesome5
      fontspec
      makecell
      orcidlink
      pdfcol
      pdflscape
      scheme-medium
      tcolorbox
      threeparttable
      threeparttablex
      tikzfill
      titling;
  });
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      quarto
      which
      pandoc;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [  tex  system_packages   ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
